recipe: default.v1
language: en
assistant_id: ultimate-quotebot-2024

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
    intent_classification: true
    entity_recognition: true
  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0.1
  - name: ResponseSelector
    epochs: 100
    retrieval_intents:
      - faq
      - chitchat

policies:
  - name: MemoizationPolicy
    max_history: 5
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
  - name: AugmentedMemoizationPolicy
    max_history: 5